server.port=${PORT:8080}

# ===============================
# KEEP ALIVE SCHEDULER
# ===============================
app.keep-alive.url=https://medical-key-development-backend.onrender.com/api/v1/version
# 14 minutes = 840000 ms
app.keep-alive.interval-ms=840000
# first ping 1 minute after startup
app.keep-alive.initial-delay-ms=60000